spring:
  profiles: 
   active:
      - dev
---  
spring:
  profiles: 
    application: 
      name: microservicecloud-config-atguigu-dev
---  
spring:
  profiles: 
    application: 
      name: microservicecloud-config-atguigu-test
